add lifecycle hooks
Koenkk/zigbee2mqtt-chart pull request #22
Opened 2024-12-07 08:22 UTC by jurgenweber

2024-12-07 09:58 UTC, jlpedrosa requested changes
hey! thanks for the PR!

We should add the documentation (by adding comments on values.yaml)
Also it would be great to add few tests since the CI now has testing.

2025-03-16 22:36 UTC, niccrane commented
Happy to pick this up if people still see value in it.

2025-03-16 22:57 UTC, jlpedrosa commented
hey @niccrane  I've never needed it, but for me there's no problem at all if people see value on it. I assume @jurgenweber  saw it that way.

2025-03-17 19:00 UTC, niccrane commented
Have opened #40 to close this off.

2025-04-07 11:21 UTC, closed without merging